- name: Add APT key
  apt_key:
    id: EA312927
    keyserver: keyserver.ubuntu.com
  tags: install
- name: Add MongoDB GPG key
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-4.4.asc
    state: present
  tags: install
- name: Add APT repository
  apt_repository:
    repo: deb [ arch=amd64 ] http://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.4 multiverse
    state: present
  tags: install
- name: Install mongodb package
  apt:
    name: mongodb-org
    state: present
  tags: install
- name: Enable MongoDB
  systemd:
    name: mongod
    enabled: true
    state: started
  tags: install
